changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - GolangBoilerPlate-Major
        - breaking-change
    - title: Exciting New Features
      labels:
        - GolangBoilerPlate-Minor
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
template: |
  ## What's Changed
  $CHANGES