name: Automatic Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          config-name: release.yml
          publish: true
          tag: ${{ github.ref }}
