name: PR Deploy
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:

jobs:
  deploy-pr:
    # environment: 
    #   name: prod
    #   url: ${{ steps.deploy.outputs.preview-url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v4
      - id: deploy
        name: Pull Request Deploy
        uses: hngprojects/pr-deploy@feat_private_key
        with:
          server_host: ${{ secrets.SERVER_HOST }}
          server_username: ${{ secrets.SERVER_USERNAME }}
          server_password: ${{ secrets.SERVER_PASSWORD }}
          server_port: ${{ secrets.SERVER_PORT }}
          server_private_key: ${{ secrets.SERVER_PRIVATE_KEY }}
          comment: true
          context: '.'
          dockerfile: 'Dockerfile'
          exposed_port: '8019'
          host_volume_path: '/var/'
          container_volume_path: '/var/'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Preview Url
        run: |
          echo "Preview Url: ${{ steps.deploy.outputs.preview-url }}"