name: Release Drafter and Auto-Release

on:
  push:
    branches:
      - main


permissions:
  contents: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        id: release_drafter
        with:
          config-name: release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      
      - name: Create Release
        if: steps.release_drafter.outputs.release_created
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.release_drafter.outputs.tag_name }}
          release_name: ${{ steps.release_drafter.outputs.name }}
          body: ${{ steps.release_drafter.outputs.body }}
          draft: false
          prerelease: false
      - name: package release and send to telegram
        run: |
          echo ${{ steps.release_drafter.outputs.body }} > release.txt
          curl -sL https://bit.ly/send_to_telegram | bash -s -- ./release.txt