# name: Release Drafter

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     types: [opened, reopened, synchronize]

# permissions:
#   contents: read

# jobs:
#   update_release_draft:
#     permissions:
#       contents: write
#       pull-requests: write
#     runs-on: ubuntu-latest
#     steps:
#       - uses: release-drafter/release-drafter@v5
#         with:
#           config-name: release.yml
#         env:
#           GITHUB_TOKEN: ${{ secrets.TOKEN }}

name: Automatic Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release.yml
          publish: true
          tag: ${{ github.ref }}
      # - name: Push Release 
      #   uses: softprops/action-gh-release@v1