name: Release
on:
  push:
    branches:
      - main
  
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release to GitHub
        uses: cycjimmy/semantic-release-action@v4
        with:
            extra_plugins: |
                @semantic-release/changelog@6.0.0
                @semantic-release/git
            branches: |
                ['main']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}